%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%% file: read_tsi_aim.m
%% author: S. Takahama
%% date: Feb 2014
%% prepared for ENV-400 exercise
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function sizeinfo = read_tsi_aim(filename, delimiter)
  %% filename is assumed to be a file generated by TSI AIM software
  %%   and contains number concentrations
  %% file is exported from TSI AIM as a comma-separated table
  %%   in row-wise orientation
  %% sizeinfo is a struct that contains the following attributions:
  %%   datetime_smps is an internal representation of times
  %%   diam_smps is a vector of diameters
  %%   numconc_smps is a matrix of number concentrations (dN/dlogDp)
  %%   totalnumc_smps is the total number concentration (#/cm^3)
  %% this function is currently not compatible with Octave for conflicts in 
  %%   behavior of textscan() and datenum()
  %% example usage:
  %%   sizes = read_tsi_aim(filename);
  %%   plot(sizes.datetime_smps,sizes.totalnumc_smps);
  %%   datetick('x');

  if nargin < 2,
    delimiter = ','
  end
  
  %% define helper function to find matching string
  strindex = @(tokens,string) ...
	      find(cellfun(@(x) ~isempty(x),strfind(tokens,string)));

  %% is Octave?
  isOctave = exist('OCTAVE_VERSION') ~= 0;

  %% in case MATLAB version < R2013a+
  strsplit = @(str,delimiter) regexp(str,delimiter,'split');

  %%  open file
  fid = fopen(filename);

				% read metadata
  line_ = '';
  while ~feof(fid),
    line_ = fgetl(fid);
    if ~isempty(strfind(line_,'Sample #')),
      break
    end
  end
  tokens = strsplit(line_,delimiter);
  iDiam = find(cellfun(@(x) ~isempty(str2num(x)),tokens));
  diam = cellfun(@str2num,tokens(iDiam));
  %% define format and read values
  format_ = strcat(repmat('%s',1,iDiam(1)-1),...
		   repmat('%f',1,length(diam)),...
		   repmat('%s',1,length(tokens)-iDiam(length(iDiam))));
  data = textscan(fid,format_,'delimiter',delimiter);

  %% close file
  fclose(fid);

  %% read number concentration
  numconc = cell2mat(data(iDiam));

  %% parse date/time string
  datetime = datenum(strcat(data{2},{' '},data{3}),'mm/dd/yy HH:MM:SS');
				%time = datenum(data{3},'HH:MM:SS');
  time_format = datestr(data{3},'HH:MM:SS');
  %% find and extract total number concentration
  tmpvar = data{strindex(tokens,'Total')};
  totalnumc = cellfun(@str2num,regexprep(tmpvar,'\(.+\)',''));

  %% create structure to be returned from function
  sizeinfo = struct('datetime',datetime,'time_format',time_format,'diam',diam, ...
		    'numconc',numconc, 'totalnumc',totalnumc);

  return
