
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%% file: read_opc.m
%% author: S. Takahama, G. Ergin
%% date:May 2015
%% prepared for Radon project
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function opc = read_opc_xls(filename, dilutionfactor)
  %% filename is assumed to be a file generated by OPC instrument's software
  %%   and contains number concentrations
  %% radon is a struct that contains the following attributions:
  %%   time_opc_num is an internal representation of Matlab times
  %%   diam_opc is a vector of diameters
  %%   numconc_opc is a matrix of number concentrations 
  %% example usage:
  %%   opc = read_opc(xlsfilename);
  %%   plot(opc.diam,opc.numconc);
  %%   plot(opc.time,opc.numconc(:,1));
  %%   datetick('x');

  if nargin < 2,
    dilutionfactor = 1;
  end 

  %%read from .xlsx file
  [date, header] = xlsread(filename,'A:A');
  [time, header] = xlsread(filename,'B:B');
  [volume, header] = xlsread(filename,'O:O');
  [lt5coinc, header] = xlsread(filename,'L:L');
  [data, header] = xlsread(filename,'Q:AB');
  Time_opc = strcat(datestr(datetime(date,'ConvertFrom','excel'),'yyyy.mm.dd'),...
		    {' '},datestr(time,'HH:MM:SS'));
  %% convert time to Matlab time
  fmt = 'yyyy.mm.dd HH:MM:SS';
  Time = datenum(Time_opc,fmt);
  formatted_time = datestr(Time,fmt);
  k=0;
		       %extract diameter and number concentration data
  for i = (1:2:size(data,2)-1)
    k = k+1;
    Diam(k)  = mean(data(:,i))*1e3;        % um to nm
    Nconc(:,k) = data(:,i+1)./volume*1e-6; % # to #/m^3 to #/cm^3
  end 
  %% create structure to be returned from function
  opc = struct('time',Time,...
	       'diam',Diam, ...
	       'numconc',Nconc,...
	       'lt5coinc',lt5coinc,...
	       'formatted_time',formatted_time); 
  return
