
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%% file: read_opc.m
%% author: S. Takahama, G. Ergin
%% date:May 2015
%% prepared for Radon project
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function opc = read_opc_csv(filename,dilutionfactor)
  %% filename is assumed to be a file generated by OPC instrument's software
  %%   and contains number concentrations
  %% radon is a struct that contains the following attributions:
  %%   time_opc_num is an internal representation of Matlab times
  %%   diam_opc is a vector of diameters
  %%   numconc_opc is a matrix of number concentrations 
  %% example usage:
  %%   opc = read_opc(csvfilename);
  %%   plot(opc.diam,opc.numconc);
  %%   plot(opc.time,opc.numconc(:,1));
  %%   datetick('x');

  if nargin < 2,
    dilutionfactor = 1;
  end 

  %% read from .csv file
  contents = readtable(filename);
  Time = datenum(strcat(contents.x_SampleDate_,{' '},contents.x_SampleTime_),...
		 'dd/mm/yy HH:MM:SS');
  formatted_time = datestr(Time,'yyyy.mm.dd HH:MM:SS');
  lt5coinc = contents.x__5Coinc__;
  maxsize = 6;
  for k=1:maxsize,
    Diam(k) = mean(contents.(sprintf('x_Size%d_',k)))*1e3; % um to nm
    Nconc(:,k) = contents.(sprintf('x_Counts%d_',k))./...
		 contents.x_SampleVolume_*1e-6/dilutionfactor; % # to #/m^3 to #/cm^3    
  end

  %% create structure to be returned from function
  opc = struct('time',Time,...
	       'diam',Diam, ...
	       'numconc',Nconc,...
	       'lt5coinc',lt5coinc,...
	       'formatted_time',formatted_time); 
  return
